name: CI/CD

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: videos_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        env:
          DB_NAME: videos_test
          DB_USER: postgres
          DB_PASSWORD: test_password
          DB_HOST: localhost
          REDIS_HOST: localhost
        run: pytest --cov=. --cov-report=xml
      - uses: codecov/codecov-action@v3

  build-and-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t endoflix:test .
      - name: Test Docker image
        run: |
          docker run -d --name test-postgres -e POSTGRES_DB=videos_test -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=test_password -p 5432:5432 postgres:15-alpine
          docker run -d --name test-redis -p 6379:6379 redis:7-alpine
          sleep 10
          docker run --name test-endoflix -e DB_HOST=host.docker.internal -e DB_NAME=videos_test -e DB_USER=postgres -e DB_PASSWORD=test_password -e REDIS_HOST=host.docker.internal -p 5000:5000 endoflix:test
          sleep 15
          curl -f http://localhost:5000/health || exit 1
      - name: Clean up
        run: |
          docker stop test-endoflix test-redis test-postgres || true
          docker rm test-endoflix test-redis test-postgres || true